// Real-browser regression run by npm run test:ui, with fake responses and no paid API calls.
import assert from 'node:assert/strict';
import { mkdtempSync,mkdirSync,rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import puppeteer from 'puppeteer-core';
import { createApp } from '../server.mjs';
import { browserPath } from '../lib/research-tools.mjs';
import { input,report,ChatProvider,chatResponse } from './fixtures.mjs';

const dir=mkdtempSync(path.join(os.tmpdir(),'ahj-chat-ui-')),releases=[];
// Later phases replace the held replies with their own behavior.
let custom=null;
const provider=new ChatProvider((payload,n,options)=>custom?custom(payload,n,options):new Promise(resolve=>releases.push(()=>{
  const source=payload.messages[0].content.find(b=>b.type==='search_result');
  resolve(chatResponse('',{content:[{type:'text',text:`**${n===2?'BRAVO':'ALPHA'} reply**\nThe saved source describes this project [S1].\n<img src=x onerror="window.injected=true">`,citations:[{type:'search_result_location',source:source.source,title:source.title,cited_text:source.content[0].text,search_result_index:0,start_block_index:0,end_block_index:1}]}]}));
})));
let app,browser,page,phase='setup';
try{
  app=await createApp({dataDir:dir,port:0,provider,worker:false});
  const create=name=>{const p=app.store.create({...input,name});app.store.updateProject(p.id,{status:'complete',report:{...report(),summary:name+' synthetic report.'}});for(const s of app.store.stages(p.id))app.store.updateStage(p.id,s.id,{status:'complete'});app.store.source(p.id,{url:'https://example.com/'+name,title:name+' source',text:name+' evidence from the saved record. <img src=x onerror="window.injected=true">',readFull:true});return p;};
  const a=create('ALPHA project'),b=create('BRAVO project'),cp=create('CHARLIE project');
  app.store.updateProject(cp.id,{report:{...report(),summary:'CHARLIE project synthetic report.',gaps:[{question:'Which NFPA 13 edition does the fire marshal enforce?',why:'Design basis',contact:'Fire marshal',nextStep:'Confirm the edition.'}]}});
  browser=await puppeteer.launch({executablePath:browserPath(),headless:true,pipe:true});page=await browser.newPage();await page.setViewport({width:1440,height:1100});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  phase='required name';await page.goto(app.url);await page.waitForSelector('#name');assert.equal(await page.$eval('#name',e=>e.required),true);assert.ok(!/optional/.test(await page.$eval('label[for=name]',e=>e.textContent)));assert.equal(await page.$eval('#name',e=>e.checkValidity()),false);
  const click=selector=>page.locator(selector).click();
  phase='project drafts';await click(`[data-project="${a.id}"]`);await click('[data-tab=chat]');await page.waitForSelector('#chat-message');await page.type('#chat-message','ALPHA unsent message');
  await click(`[data-project="${b.id}"]`);await page.waitForFunction(()=>document.querySelector('.chat-heading h2')?.textContent.includes('BRAVO'));assert.equal(await page.$eval('#chat-message',e=>e.value),'');await page.type('#chat-message','BRAVO independent message');
  await click(`[data-project="${a.id}"]`);await page.waitForFunction(()=>document.querySelector('.chat-heading h2')?.textContent.includes('ALPHA'));assert.equal(await page.$eval('#chat-message',e=>e.value),'ALPHA unsent message');
  phase='concurrent isolated replies';await click('#chat-form button[type=submit]');await page.waitForSelector('#chat-stop');assert.equal(await page.$eval('#chat-message',e=>e.disabled),true);
  await click(`[data-project="${b.id}"]`);await page.waitForFunction(()=>document.querySelector('.chat-heading h2')?.textContent.includes('BRAVO'));assert.equal(await page.$eval('#chat-message',e=>e.value),'BRAVO independent message');assert.ok(!(await page.$eval('#report-content',e=>e.innerText)).includes('ALPHA'));await click('#chat-form button[type=submit]');await page.waitForSelector('#chat-stop');
  while(releases.length<2)await new Promise(r=>setTimeout(r,5));assert.equal(provider.calls.length,2);assert.ok(!JSON.stringify(provider.calls[0].payload).includes('BRAVO'));assert.ok(!JSON.stringify(provider.calls[1].payload).includes('ALPHA'));
  releases[1]();await page.waitForFunction(()=>document.querySelector('#chat-history')?.textContent.includes('BRAVO reply'),{timeout:10000});assert.equal(await page.evaluate(()=>Boolean(window.injected)),false);assert.equal(await page.$('#chat-history img'),null);
  await click(`[data-project="${a.id}"]`);await page.waitForFunction(()=>document.querySelector('.chat-heading h2')?.textContent.includes('ALPHA'));assert.ok(!(await page.$eval('#chat-history',e=>e.innerText)).includes('BRAVO'));releases[0]();await page.waitForFunction(()=>document.querySelector('#chat-history')?.textContent.includes('ALPHA reply'),{timeout:10000});
  phase='citations and reload';await click('#chat-history .chat-citation summary');assert.match(await page.$eval('#chat-history .chat-citation blockquote',e=>e.textContent),/ALPHA project evidence/);assert.equal(await page.$('#chat-history .chat-citation img'),null);assert.equal(await page.evaluate(()=>Boolean(window.injected)),false);
  await click('#chat-history .chat-citation [data-source=S1]');await page.waitForSelector('#source-S1');assert.match(await page.$eval('#source-S1',e=>e.textContent),/ALPHA project source/);await click('[data-tab=chat]');await page.reload();await click('[data-tab=chat]');assert.match(await page.$eval('#chat-history',e=>e.textContent),/ALPHA reply/);await click('#chat-history .chat-citation summary');assert.match(await page.$eval('#chat-history .chat-citation blockquote',e=>e.textContent),/ALPHA project evidence/);
  phase='reply depth';assert.deepEqual(await page.$$eval('#chat-mode option',o=>o.map(x=>x.value)),['standard','economy','opus']);assert.deepEqual(await page.$$eval('#chat-mode option',o=>o.map(x=>x.textContent)),['Standard — Claude Sonnet 5.5, high reasoning','Economy — Claude Haiku 5.5, medium reasoning','Premium — Claude Opus 5.5, high reasoning']);assert.match(await page.$eval('#chat-mode-help',e=>e.textContent),/Sonnet 5\.5 · High reasoning/);await page.select('#chat-mode','opus');assert.match(await page.$eval('#chat-mode-help',e=>e.textContent),/Opus 5\.5 · High reasoning/);
  phase='stop reply';await page.type('#chat-message','A second ALPHA question');await click('#chat-form button[type=submit]');await page.waitForSelector('#chat-stop');while(releases.length<3)await new Promise(r=>setTimeout(r,5));await click('#chat-stop');await page.waitForFunction(()=>document.querySelector('#chat-history')?.textContent.includes('Stopping after the current request'));releases[2]();await page.waitForFunction(()=>!document.querySelector('#chat-stop'),{timeout:10000});assert.equal(app.services.chat.view(a.id).turns.at(-1).status,'stopped');assert.equal(provider.calls[2].payload.model,'claude-opus-5-5');assert.match(await page.$eval('#chat-history',e=>e.textContent),/Premium · Claude Opus 5\.5/);assert.equal(await page.$eval('#chat-mode',e=>e.value),'opus');
  phase='late project response';await click(`[data-project="${b.id}"]`);await page.waitForFunction(()=>document.querySelector('.chat-heading h2')?.textContent.includes('BRAVO'));
  await page.setRequestInterception(true);let held=null,holdA=true;
  page.on('request',req=>{if(holdA&&req.url()===app.url+'/api/projects/'+a.id){holdA=false;held=req;}else req.continue();});
  await click(`[data-project="${a.id}"]`);while(!held)await new Promise(r=>setTimeout(r,5));await click(`[data-project="${b.id}"]`);await page.waitForFunction(()=>document.querySelector('.chat-heading h2')?.textContent.includes('BRAVO'));await held.continue();await new Promise(r=>setTimeout(r,300));assert.match(await page.$eval('.chat-heading h2',e=>e.textContent),/BRAVO/);assert.ok(!(await page.$eval('#chat-history',e=>e.textContent)).includes('ALPHA'));
  phase='estimated costs without budgets';assert.doesNotMatch(await page.$eval('#main',e=>e.innerText),/budget|allowance/i);assert.match(await page.$eval('.chat-send-row',e=>e.textContent),/estimated for this project · \$[\d.]+ from chat/);
  await click('#settings-top');await page.waitForFunction(()=>document.querySelector('#spending-summary')?.textContent.includes('TODAY'));assert.doesNotMatch(await page.$eval('#settings-dialog',e=>e.innerText),/budget|allowance/i);await click('[data-close=settings-dialog]');
  phase='markdown and live draft';let finishLive=null;
  const table='| Standard | Edition | Adopting instrument | Effective date | Local amendments | Notes |\n|---|---|---|---|---|---|\n| NFPA 13 | 2022 | Ordinance 2024-15 adopting the International Fire Code by reference | January 1, 2025 | Section 903.2 amended for high-piled storage | Applies to new construction and alterations |';
  custom=(payload,n,{onEvent})=>new Promise(resolve=>{
    finishLive=()=>resolve(chatResponse(`### Adopted editions\n\n- NFPA 13: 2022\n- NFPA 72: 2019\n\n${table}\n`));
    onEvent({type:'message_start',message:{}});onEvent({type:'content_block_start',index:0,content_block:{type:'text',text:''}});onEvent({type:'content_block_delta',index:0,delta:{type:'text_delta',text:'**Streaming BRAVO'}});
    setTimeout(()=>onEvent({type:'content_block_delta',index:0,delta:{type:'text_delta',text:' draft**'}}),1100);
  });
  await page.type('#chat-message','Compare the adopted editions.');await click('#chat-form button[type=submit]');
  await page.waitForFunction(()=>document.querySelector('[data-chat-draft] strong')?.textContent==='Streaming BRAVO draft',{timeout:10000});
  assert.equal(await page.$eval('[data-chat-step]',e=>e.textContent),'Writing the answer…');assert.ok(await page.$('#chat-stop'));
  finishLive();await page.waitForFunction(()=>document.querySelector('#chat-history .chat-table table'),{timeout:10000});
  assert.equal(await page.$('[data-chat-draft]'),null);assert.equal(await page.$$eval('#chat-history h5',h=>h.at(-1)?.textContent),'Adopted editions');
  assert.equal(await page.$$eval('#chat-history .chat-table th',th=>th.length),6);assert.ok(await page.$$eval('#chat-history li',li=>li.some(l=>l.textContent==='NFPA 72: 2019')));
  phase='declined reply and retry';let retried=null;
  custom=()=>chatResponse('Partial text',{stop_reason:'refusal',stop_details:{type:'refusal',category:'general_harms'}});
  await page.type('#chat-message','A question Claude declines.');await click('#chat-form button[type=submit]');
  await page.waitForFunction(()=>document.querySelector('#chat-history')?.textContent.includes('Declined by Claude'),{timeout:10000});
  assert.match(await page.$$eval('.chat-declined',e=>e.at(-1).textContent),/usage-policy safeguard \(general_harms\)/);assert.ok(!(await page.$eval('#chat-history',e=>e.textContent)).includes('Partial text'));
  assert.equal(await page.$eval('[data-chat-retry]',e=>e.textContent),'Try again with Premium');
  custom=payload=>{retried=payload;return chatResponse('Opus answer after the decline.');};
  await click('[data-chat-retry]');await page.waitForFunction(()=>document.querySelector('#chat-history')?.textContent.includes('Opus answer after the decline.'),{timeout:10000});
  assert.equal(retried.model,'claude-opus-5-5');assert.match(retried.messages.at(-1).content.at(-1).text,/A question Claude declines\./);custom=null;
  // Once the message has been sent to the other model, the declined reply no longer offers it.
  assert.equal(await page.$('[data-chat-retry]'),null);await page.reload();await click('[data-tab=chat]');await page.waitForSelector('#chat-history');assert.equal(await page.$('[data-chat-retry]'),null);
  phase='economy reply and refusal retry';
  await page.select('#chat-mode','economy');assert.match(await page.$eval('#chat-mode-help',e=>e.textContent),/Haiku 5\.5 · Medium reasoning/);
  assert.match(await page.$eval('#chat-limits',e=>e.textContent),/input\/output cost \$0\.10\/\$0\.50.*100,000 tokens.*\$0\.50\/\$2\.50/);
  assert.doesNotMatch(await page.$eval('#chat-limits',e=>e.textContent),/Both depths/);
  let economyPayload=null;
  custom=payload=>{economyPayload=payload;return chatResponse('Economy summary of the saved project.');};
  await page.type('#chat-message','Summarize the saved project using Economy.');await click('#chat-form button[type=submit]');
  await page.waitForFunction(()=>document.querySelector('#chat-history')?.textContent.includes('Economy summary of the saved project.'),{timeout:10000});
  assert.equal(economyPayload.model,'claude-haiku-5-5');assert.equal(economyPayload.output_config.effort,'medium');assert.deepEqual(economyPayload.thinking,{type:'adaptive',display:'omitted'});
  assert.ok(economyPayload.tools.some(t=>t.name==='read_saved_source'));assert.ok(economyPayload.tools.some(t=>t.name==='web_search'));assert.ok(economyPayload.tools.some(t=>t.name==='propose_question_update'));
  assert.match(await page.$eval('#chat-history',e=>e.textContent),/Economy · Claude Haiku 5\.5/);
  await page.reload();await click('[data-tab=chat]');await page.waitForSelector('#chat-mode');
  assert.match(await page.$eval('#chat-history',e=>e.textContent),/Economy · Claude Haiku 5\.5/);assert.equal(await page.$eval('#chat-mode',e=>e.value),'standard');
  await page.select('#chat-mode','economy');custom=()=>chatResponse('',{stop_reason:'refusal',stop_details:{type:'refusal',category:'general_harms'}});
  await page.type('#chat-message','An Economy question Claude declines.');await click('#chat-form button[type=submit]');
  await page.waitForFunction(()=>document.querySelector('[data-chat-retry]')?.textContent==='Try again with Standard',{timeout:10000});
  custom=payload=>{retried=payload;return chatResponse('Standard answer after the Economy decline.');};
  await click('[data-chat-retry]');await page.waitForFunction(()=>document.querySelector('#chat-history')?.textContent.includes('Standard answer after the Economy decline.'),{timeout:10000});
  assert.equal(retried.model,'claude-sonnet-5-5');assert.equal(retried.output_config.effort,'high');assert.equal(await page.$('[data-chat-retry]'),null);custom=null;
  phase='proposal cards';
  const questionId=app.store.project(cp.id).questions[0].id;
  custom=payload=>payload.messages.at(-1).content.some(x=>x.type==='tool_result')?chatResponse('Two cards are ready for your approval.'):chatResponse('',{stop_reason:'tool_use',content:[
    {type:'tool_use',id:'toolu_answer',name:'propose_question_update',input:{questionId,status:'answered',answer:'NFPA 13, 2025 edition <img src=x onerror="window.injected=true">',reason:'You confirmed the edition with the fire marshal.'}},
    {type:'tool_use',id:'toolu_round',name:'propose_research_round',input:{focus:'clarification',clarification:'Owner confirmed a hyperscale data center.',reason:'The saved report predates this context.'}}]});
  await click(`[data-project="${cp.id}"]`);await page.waitForFunction(()=>document.querySelector('.chat-heading h2')?.textContent.includes('CHARLIE'));
  await page.type('#chat-message','I confirmed NFPA 13, 2025 edition with the fire marshal.');await click('#chat-form button[type=submit]');
  await page.waitForFunction(()=>document.querySelectorAll('.chat-proposal').length===2,{timeout:10000});
  assert.equal(await page.evaluate(()=>Boolean(window.injected)),false);assert.equal(await page.$('.chat-proposal img'),null);assert.match(await page.$eval('.chat-proposal .chat-proposal-text',e=>e.textContent),/<img src=x/);
  assert.deepEqual(await page.$$eval('.chat-proposal h3',h=>h.map(x=>x.textContent)),['Answer a question','Start a research round']);
  assert.deepEqual(await page.$$eval('[data-proposal-apply]',b=>b.map(x=>x.textContent)),['Apply','Apply and start research']);assert.deepEqual(await page.$$eval('[data-proposal-mode] option',o=>o.map(x=>x.value)),['realtime','batch']);
  assert.equal(app.store.project(cp.id).questions[0].status,'open');assert.equal(app.store.project(cp.id).status,'complete');
  await click('[data-proposal-apply]');await page.waitForFunction(()=>document.querySelector('.chat-proposal .status-pill.green')?.textContent.startsWith('Applied'),{timeout:10000});
  let saved=app.store.project(cp.id).questions[0];assert.equal(saved.status,'answered');assert.match(saved.answer,/^NFPA 13, 2025 edition/);
  // A running reply holds the paid card; research cannot be changed while chat answers.
  let finishHeld=null;custom=()=>new Promise(resolve=>{finishHeld=()=>resolve(chatResponse('Held reply finished.'));});
  await page.type('#chat-message','Anything else to confirm?');await click('#chat-form button[type=submit]');await page.waitForSelector('#chat-stop');
  await page.waitForFunction(()=>document.querySelector('[data-proposal-apply]')?.disabled===true);assert.match(await page.$eval('.chat-proposal-actions .field-help',e=>e.textContent),/current reply finishes/);
  while(!finishHeld)await new Promise(r=>setTimeout(r,5));finishHeld();await page.waitForFunction(()=>document.querySelector('#chat-history')?.textContent.includes('Held reply finished.'),{timeout:10000});
  await page.waitForFunction(()=>document.querySelector('[data-proposal-apply]')?.disabled===false,{timeout:10000});
  app.services.engine.tick=async()=>{};await page.select('[data-proposal-mode]','batch');await click('[data-proposal-apply]');
  await page.waitForFunction(()=>document.querySelectorAll('.chat-proposal .status-pill.green').length===2,{timeout:10000});
  saved=app.store.project(cp.id);assert.equal(saved.status,'queued');assert.equal(saved.mode,'batch');assert.match(saved.input.notes,/User clarification: Proposed in project chat and approved by the user: Owner confirmed a hyperscale data center\./);
  await page.setViewport({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await page.setViewport({width:1440,height:1100});
  await page.reload();await click('[data-tab=chat]');await page.waitForSelector('.chat-proposal');assert.equal(await page.$$eval('.chat-proposal .status-pill.green',e=>e.length),2);assert.equal(await page.$('[data-proposal-apply]'),null);custom=null;
  phase='report note';
  custom=payload=>payload.messages.at(-1).content.some(x=>x.type==='tool_result')?chatResponse('A note card is ready.'):chatResponse('',{stop_reason:'tool_use',content:[{type:'tool_use',id:'toolu_note',name:'propose_report_note',input:{title:'Sprinkler <b>edition</b>',note:'The county enforces **NFPA 13, 2025 edition** [S1]. <img src=x onerror="window.injected=true">',reason:'You asked to keep this finding.'}}]});
  await page.type('#chat-message','Save the sprinkler edition finding to the report.');await click('#chat-form button[type=submit]');
  await page.waitForFunction(()=>[...document.querySelectorAll('.chat-proposal h3')].some(h=>h.textContent==='Save a note to the report'),{timeout:10000});
  assert.equal(app.store.notes(cp.id).length,0);assert.deepEqual(await page.$$eval('[data-proposal-apply]',b=>b.map(x=>x.textContent)),['Apply']);
  await click('[data-proposal-apply]');await page.waitForFunction(()=>document.querySelectorAll('.chat-proposal .status-pill.green').length===3,{timeout:10000});
  assert.deepEqual(app.store.notes(cp.id).map(n=>n.title),['Sprinkler <b>edition</b>']);
  // The note appears on Overview, escaped, with its citation linked to the saved source.
  await click('[data-tab=overview]');await page.waitForSelector('#report-notes');
  assert.equal(await page.$eval('#report-notes h3',e=>e.textContent),'Sprinkler <b>edition</b>');assert.equal(await page.$('#report-notes h3 b'),null);assert.equal(await page.$('#report-notes img'),null);
  assert.equal(await page.$eval('#report-notes strong',e=>e.textContent),'NFPA 13, 2025 edition');assert.ok(await page.$('#report-notes [data-source="S1"]'));assert.equal(await page.evaluate(()=>Boolean(window.injected)),false);
  page.once('dialog',dialog=>dialog.accept());await click('[data-delete-note]');await page.waitForFunction(()=>!document.querySelector('#report-notes'),{timeout:10000});
  assert.deepEqual(app.store.notes(cp.id),[]);custom=null;await click('[data-tab=chat]');await page.waitForSelector('.chat-heading');
  phase='ask atlas';
  await page.select('#chat-mode','opus');
  let asked=null;
  custom=payload=>{
    asked??=payload;
    if(payload.messages.at(-1).content.some(x=>x.type==='tool_result'))return chatResponse('The saved source supports NFPA 13, 2022. Apply the card to save it.');
    return chatResponse('',{stop_reason:'tool_use',content:[{type:'tool_use',id:'toolu_ask_atlas',name:'propose_question_update',input:{questionId,status:'answered',answer:'NFPA 13, 2022 edition, cited from the saved source [S1].',reason:'Ask Atlas found the edition in the saved source.'}}]});
  };
  await click('[data-tab=overview]');await page.waitForSelector('#saved-questions');await page.click('#saved-questions>summary');
  assert.equal(await page.$eval(`[data-question="${questionId}"] [data-ask-atlas]`,e=>e.textContent),'Ask Atlas');
  assert.match(await page.$eval('.tabs',e=>e.textContent),/Chat with Atlas/);
  assert.equal(/Chat with AI/.test(await page.$eval('#main',e=>e.textContent)),false);
  const beforeAsk=app.store.project(cp.id).questions.find(q=>q.id===questionId).answer;
  await click(`[data-question="${questionId}"] [data-ask-atlas]`);
  await page.waitForFunction(()=>document.querySelector('#chat-history')?.textContent.includes('Resolve this specific question'),{timeout:10000});
  await page.waitForFunction(()=>document.querySelector('[data-proposal-apply]')?.textContent==='Apply',{timeout:10000});
  assert.equal(await page.$$eval('.chat-user-text',(els,id)=>els.some(e=>e.textContent.includes('do the legwork yourself')&&e.textContent.includes(id)&&!e.textContent.includes('Which NFPA 13 edition does the fire marshal enforce?')),questionId),true);
  assert.equal(app.store.project(cp.id).questions.find(q=>q.id===questionId).answer,beforeAsk);
  assert.equal(asked.model,'claude-opus-5-5');assert.equal(asked.max_tokens,128000);assert.equal(asked.output_config.effort,'high');
  assert.ok(asked.tools.some(t=>t.name==='web_search'&&t.max_uses===4));assert.ok(asked.tools.some(t=>t.name==='propose_question_update'));
  assert.match(asked.system,/You are the project AI assistant/);
  await click('[data-proposal-apply]');
  await page.waitForFunction(()=>document.querySelectorAll('.chat-proposal .status-pill.green').length===4,{timeout:10000});
  assert.match(app.store.project(cp.id).questions.find(q=>q.id===questionId).answer,/NFPA 13, 2022 edition/);
  custom=null;
  await click(`[data-project="${b.id}"]`);await page.waitForFunction(()=>document.querySelector('.chat-heading h2')?.textContent.includes('BRAVO'));
  phase='desktop/mobile layout';await click('#chat-limits>summary');await page.type('#chat-message','Which missing details should I confirm with the owner?');await click('#chat-history .chat-citation summary');assert.equal(await page.$eval('#chat-history .chat-citation',e=>e.open),true);
  mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/project-chat-desktop.png',fullPage:true});await page.setViewport({width:390,height:844});await page.screenshot({path:'test-results/project-chat-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
  assert.deepEqual(errors,[]);console.log('Chat browser checks passed: required name, siloed drafts/history/replies, simultaneous project chats, source links, escaped content, reload, three reply depths including Economy payload and history reload, Economy decline retry on Standard, stop, stale-response protection, estimated costs without budgets, Markdown tables and lists, live draft and step, declined reply with retry on the other model, proposal cards applied only on Apply, a report note saved, shown on Overview and removed, Ask Atlas on a question card using the selected reply depth and Apply, Chat with Atlas label, and desktop/mobile layout. No paid API calls.');
}catch(e){console.error('Failed during: '+phase);if(page){console.error(await page.evaluate(()=>document.body.innerText).catch(()=>''));await page.screenshot({path:'test-results/project-chat-failure.png',fullPage:true}).catch(()=>{});}throw e;}
finally{for(const release of releases)release();await browser?.close();await app?.close();assert.ok(path.resolve(dir).startsWith(path.join(os.tmpdir(),'ahj-chat-ui-')));rmSync(dir,{recursive:true,force:true});}
