import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import puppeteer from 'puppeteer-core';
import { createApp } from '../server.mjs';
import { diagnosticReport } from '../lib/diagnostics.mjs';
import { researchPayload } from '../lib/prompts.mjs';
import { projectSection } from '../lib/chat.mjs';
import { browserPath } from '../lib/research-tools.mjs';
import { FakeProvider, input, report } from './fixtures.mjs';

const ORIGINAL='ORIGINAL_ASSIGNMENT';
async function setup(t){
  const dir=mkdtempSync(path.join(os.tmpdir(),'ahj-rename-test-'));
  const app=await createApp({dataDir:dir,port:0,provider:new FakeProvider(),worker:false});
  t.after(async()=>{await app.close();assert.ok(path.resolve(dir).startsWith(path.join(os.tmpdir(),'ahj-rename-test-')));rmSync(dir,{recursive:true,force:true});});
  const {token}=await(await fetch(app.url+'/api/bootstrap')).json();
  const rename=(id,name)=>fetch(app.url+'/api/projects/'+id+'/rename',{method:'POST',headers:{'Content-Type':'application/json','X-App-Token':token},body:JSON.stringify({name})});
  return {app,rename,token};
}
function runningResearch(store,project){
  const payload={model:'claude-sonnet-5-5',messages:[{role:'user',content:ORIGINAL}],tools:[{name:'web_search',max_uses:2}]};
  store.updateProject(project.id,{status:'researching',note:'Jurisdiction research is in progress.'});
  store.updateStage(project.id,'jurisdiction',{status:'running',rounds:1,output:'Saved jurisdiction brief.',messages:[{role:'user',content:ORIGINAL}]});
  const attempt=store.reserve(project.id,'jurisdiction',{mode:'realtime',modelKey:'research',payload,reserve:250000});
  store.updateAttempt(attempt.id,{state:'pending'});
  return store.attempt(attempt.id);
}

test('renaming after research starts updates every stored label and leaves the running request alone',async t=>{
  const {app,rename}=await setup(t),s=app.store,p=s.create(input),other=s.create({...input,name:'Leave this project'});
  const attempt=runningResearch(s,p),before=s.project(p.id);
  const stages=s.stages(p.id),reportBody=before.report,note=before.note;
  const next='  Westside pump room  ';
  const saved=s.renameProject(p.id,next);
  assert.equal(saved.name,'Westside pump room');
  assert.equal(saved.input.name,'Westside pump room');
  assert.equal(saved.status,'researching');
  assert.equal(saved.note,note);
  assert.equal(saved.address,before.address);
  assert.equal(saved.input.address,before.input.address);
  assert.equal(saved.input.discipline,before.input.discipline);
  assert.equal(saved.input.siteDescription,before.input.siteDescription);
  assert.equal(saved.cancel_requested,false);
  assert.equal(saved.report,reportBody);
  assert.equal(saved.cost,before.cost);
  assert.deepEqual(s.stages(p.id),stages);
  assert.deepEqual(s.attempt(attempt.id).payload,attempt.payload);
  assert.equal(s.attempt(attempt.id).state,'pending');
  assert.equal(s.project(other.id).name,'Leave this project');
  const reused=researchPayload(s,s.project(p.id),s.stage(p.id,'jurisdiction'));
  assert.equal(reused.messages[0].content,ORIGINAL);
  assert.ok(!JSON.stringify(reused).includes('Westside pump room'));
  const upcoming=JSON.stringify(researchPayload(s,s.project(p.id),s.stage(p.id,'contacts')));
  assert.match(upcoming,/Westside pump room/);
  assert.equal(projectSection(s,p.id,'context').name,'Westside pump room');
  assert.equal(projectSection(s,p.id,'context').input.name,'Westside pump room');
  assert.equal(projectSection(s,p.id,'context').status,'researching');
  const activity=s.events(p.id).find(e=>e.kind==='rename');
  assert.match(activity.message,/from “Workflow verification · synthetic data” to “Westside pump room”/);
  const diagnostics=JSON.stringify(diagnosticReport(s,{connection:{}}));
  assert.match(diagnostics,/Project name changed\. The names are omitted from diagnostics\./);
  assert.ok(!diagnostics.includes('Westside pump room'));
  assert.equal(s.renameProject(p.id,'Westside pump room').updated,saved.updated);
  assert.equal(s.events(p.id).filter(e=>e.kind==='rename').length,1);
  const response=await rename(p.id,'  Café pump room  ');
  assert.equal(response.status,200);
  const body=await response.json();
  assert.equal(body.name,'Café pump room');
  assert.equal(body.input.name,'Café pump room');
  assert.equal(body.status,'researching');
  const detail=await(await fetch(app.url+'/api/projects/'+p.id)).json();
  assert.equal(detail.project.name,'Café pump room');
  assert.equal(detail.project.input.name,'Café pump room');
  assert.equal(detail.stages.find(stage=>stage.id==='jurisdiction').status,'running');
  assert.match(detail.events[0].message,/Café pump room/);
  const listed=await(await fetch(app.url+'/api/projects')).json();
  assert.equal(listed.find(item=>item.id===p.id).name,'Café pump room');
  assert.equal(listed.find(item=>item.id===p.id).input.name,'Café pump room');
  const exported=await fetch(app.url+'/api/projects/'+p.id+'/export?format=json');
  assert.equal(exported.status,200);
  const filename=decodeURIComponent(exported.headers.get('content-disposition').match(/filename\*=UTF-8''([^;]+)/)[1]);
  assert.match(filename,/^Café pump room - AHJ research\.json$/);
  const data=await exported.json();
  assert.equal(data.project.name,'Café pump room');
  assert.equal(data.project.context.name,'Café pump room');
  assert.equal(data.report,null);
  assert.deepEqual(s.attempt(attempt.id).payload,attempt.payload);
});

test('renaming a finished project keeps the saved report and completed stages',async t=>{
  const {app,rename}=await setup(t),s=app.store,p=s.create(input);
  const finished=report();finished.summary='Report for '+input.name;
  s.updateProject(p.id,{status:'complete',report:finished});
  for(const stage of s.stages(p.id))s.updateStage(p.id,stage.id,{status:'complete',output:stage.id+' brief'});
  const stages=s.stages(p.id),before=structuredClone(s.project(p.id).report);
  const response=await rename(p.id,'Finished label');
  assert.equal(response.status,200);
  const saved=s.project(p.id);
  assert.equal(saved.name,'Finished label');
  assert.equal(saved.input.name,'Finished label');
  assert.equal(saved.status,'complete');
  assert.deepEqual(saved.report,before);
  assert.equal(saved.report.summary,'Report for '+input.name);
  assert.deepEqual(s.stages(p.id),stages);
  const data=await(await fetch(app.url+'/api/projects/'+p.id+'/export?format=json')).json();
  assert.equal(data.project.name,'Finished label');
  assert.equal(data.project.context.name,'Finished label');
  assert.equal(data.report.summary,'Report for '+input.name);
});

test('rename uses the same name rules and does not partially write',async t=>{
  const {app,rename}=await setup(t),s=app.store,p=s.create(input);
  runningResearch(s,p);
  for(const name of [undefined,'','   ','\n','x'.repeat(101),'Unsafe\nname']){
    assert.throws(()=>s.renameProject(p.id,name),/project name/);
    assert.equal((await rename(p.id,name)).status,400);
    assert.equal(s.project(p.id).name,input.name);
    assert.equal(s.project(p.id).input.name,input.name);
  }
  assert.equal((await fetch(app.url+'/api/projects/'+p.id+'/rename',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Nope'})})).status,403);
  assert.equal((await rename('00000000-0000-4000-8000-000000000000','Nope')).status,404);
  assert.equal(s.project(p.id).status,'researching');
  s.db.exec("CREATE TRIGGER prevent_rename BEFORE UPDATE ON projects BEGIN SELECT RAISE(ABORT,'Test failure'); END;");
  assert.throws(()=>s.renameProject(p.id,'Should not stick'));
  assert.equal(s.project(p.id).name,input.name);
  assert.equal(s.events(p.id).some(e=>e.kind==='rename'),false);
  s.db.exec('DROP TRIGGER prevent_rename');
  assert.equal(s.renameProject(p.id,'Should stick').name,'Should stick');
});

test('the project page can rename while research is running and after it is finished',async t=>{
  const dir=mkdtempSync(path.join(os.tmpdir(),'ahj-rename-ui-'));
  const app=await createApp({dataDir:dir,port:0,provider:new FakeProvider(),worker:false});
  let browser;
  t.after(async()=>{await browser?.close();await app.close();rmSync(dir,{recursive:true,force:true});});
  const s=app.store,running=s.create({...input,name:'Running synthetic project'}),finished=s.create({...input,name:'Finished synthetic project'});
  const attempt=runningResearch(s,running);
  const finishedReport=report();finishedReport.summary='Finished synthetic report body';
  s.updateProject(finished.id,{status:'complete',report:finishedReport});
  for(const stage of s.stages(finished.id))s.updateStage(finished.id,stage.id,{status:'complete',output:'Saved'});
  browser=await puppeteer.launch({executablePath:browserPath(),headless:true,pipe:true,args:process.platform==='linux'?['--no-sandbox']:[],env:{...process.env,XDG_CONFIG_HOME:path.join(dir,'config')}});
  const page=await browser.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  const click=selector=>page.evaluate(sel=>document.querySelector(sel).click(),selector);
  await page.setViewport({width:1440,height:1000});
  await page.goto(app.url+'/#project='+encodeURIComponent(running.id));
  await page.waitForSelector('#project-name');
  assert.equal(await page.$eval('#project-name',e=>e.disabled),false);
  assert.equal(await page.$eval('#project-name',e=>e.value),'Running synthetic project');
  assert.equal(await page.$eval('#save-project-name',e=>e.disabled),true);
  assert.equal(await page.$eval('#cancel-research',e=>e.textContent),'Stop research');
  await page.focus('#project-name');
  await page.keyboard.press('End');
  await page.keyboard.type(' draft');
  s.updateProject(running.id,{note:'Synthetic progress update.'});
  await page.waitForFunction(()=>document.querySelector('.notice')?.textContent.includes('Synthetic progress update.'),{timeout:10000});
  assert.equal(await page.$eval('#project-name',e=>e.value),'Running synthetic project draft');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'project-name');
  await page.setRequestInterception(true);
  let rejectSave=true;
  page.on('request',req=>{if(rejectSave&&req.url().endsWith('/rename')&&req.method()==='POST'){rejectSave=false;req.respond({status:400,contentType:'application/json',body:JSON.stringify({error:'Synthetic rename failure. Please retry.'})});}else req.continue();});
  await click('#save-project-name');
  await page.waitForFunction(()=>document.querySelector('#rename-error')?.textContent.includes('Synthetic rename failure'));
  assert.equal(await page.$eval('#project-name',e=>e.value),'Running synthetic project draft');
  assert.equal(s.project(running.id).name,'Running synthetic project');
  await click('#save-project-name');
  await page.waitForFunction(()=>document.querySelector('#toast')?.textContent==='Project name saved.');
  assert.equal(s.project(running.id).name,'Running synthetic project draft');
  assert.equal(s.project(running.id).input.name,'Running synthetic project draft');
  assert.equal(s.project(running.id).status,'researching');
  assert.equal(s.stage(running.id,'jurisdiction').status,'running');
  assert.equal(s.stage(running.id,'jurisdiction').output,'Saved jurisdiction brief.');
  assert.deepEqual(s.attempt(attempt.id).payload,attempt.payload);
  assert.equal(s.attempt(attempt.id).state,'pending');
  assert.equal(await page.$eval(`[data-project="${running.id}"] strong`,e=>e.textContent),'Running synthetic project draft');
  await click('[data-tab=chat]');
  await page.waitForSelector('.chat-heading h2');
  assert.match(await page.$eval('.chat-heading h2',e=>e.textContent),/Running synthetic project draft/);
  await click('[data-tab=activity]');
  await page.waitForFunction(()=>document.querySelector('.activity')?.textContent.includes('Project renamed from “Running synthetic project” to “Running synthetic project draft”'));
  assert.match(await page.$eval('.activity',e=>e.textContent),/Project renamed from “Running synthetic project” to “Running synthetic project draft”/);
  await click(`[data-project="${finished.id}"]`);
  await page.waitForFunction(()=>document.querySelector('#project-name')?.value==='Finished synthetic project');
  assert.equal(await page.$eval('#project-name',e=>e.disabled),false);
  await page.$eval('#project-name',e=>{e.value='Finished label';e.dispatchEvent(new Event('input',{bubbles:true}));});
  await click('#save-project-name');
  await page.waitForFunction(()=>document.querySelector('#project-name')?.value==='Finished label');
  assert.equal(s.project(finished.id).status,'complete');
  assert.equal(s.project(finished.id).report.summary,'Finished synthetic report body');
  assert.ok(s.stages(finished.id).every(stage=>stage.status==='complete'));
  await page.setViewport({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
  assert.deepEqual(errors,[]);
  assert.equal(app.services.engine.running.size,0);
});
